import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/Header/Header";
import about_sectionBg from "../public/about_sectionBg.png";
import styles from "../styles/Contactus.module.css";

export default function Contactus() {
  return (
    <>
      <Head>
        <title>WELCARE REHAB - Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <header className="header_outer">
        <Header />
      </header>
      <main>
        {/*  ##### CONTACT SECTION START ##### */}
        <section className="section_Outer">
          {/* <div className={styles.about_sectionImg_outer}>
            <div className={styles.sectionDiv} style={{ backgroundImage: `url(${about_sectionBg.src})` }}>
              <div className={styles.aboutUs_heading_wrapperBox}>
                <h1>Contact US</h1>
              </div>
            </div>
          </div>
          <div className={styles.Contact_Container_outer}>
            <div className={styles.contact_container_inner}></div>
          </div> */}
        </section>
        {/*  ##### CONTACT SECTION END ##### */}
      </main>
      {/* <footer className="footer_outer">
        <Footer />
      </footer> */}
    </>
  );
}
