import Head from "next/head";
import About from "../components/Aboutus/About";
import Footer from "../components/footer/Footer";
import Header from "../components/Header/Header";
import about_sectionBg from "../public/about_sectionBg.png";
import styles from "../styles/Gallery.module.css";
import Product from "../components/Product/Product";
import Gallery from "../components/Gallery/Gallery";

export default function GalleryPage() {
  return (
    <>
      <Head>
        <title>WELCARE REHAB - Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <header className="header_outer">
        <Header />
      </header>
      <main>
        {/*  ##### ABOUT SECTION START ##### */}
        <section className={styles.section_Outer2}>
          <div className={styles.product_sectionImg_outer}>
            <div className={styles.sectionDiv} style={{ backgroundImage: `url(${about_sectionBg.src})` }}>
              <div className={styles.product_heading_wrapperBox}>
                <h1>Gallery</h1>
              </div>
            </div>
          </div>
          <Gallery />
        </section>
        {/*  ##### ABOUT SECTION END ##### */}
      </main>
      <footer className="footer_outer">
        <Footer />
      </footer>
    </>
  );
}
