import Head from "next/head";
import About from "../components/Aboutus/About";
import Footer from "../components/footer/Footer";
import Gallery from "../components/Gallery/Gallery";
import Header from "../components/Header/Header";
import Product from "../components/Product/Product";
import section2 from "../public/section2.png";
import locationIcon from "../public/locationIcon.png";
import phoneIcon from "../public/phoneIcon.png";
import emailIcon from "../public/emailIcon.png";
import herobg from "../public/heroBg.png";
import background_banner from "../public/background-banner.png";
import bgImage from "../public/mainBg.png";
import aboutus_outer from "../public/aboutus_outer.png";

import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const slides = [
    {
      image: herobg.src,
      h1: 'WELCOME TO "WELCARE REHAB"',
      p: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here",
    },
    {
      image: bgImage.src,
      h1: "Lorem Ipsum is simply dummy ",
      p: " Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.",
    },
    // ...
  ];
  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentIndex((currentIndex + 1) % slides.length);
    }, 10000);
    return () => clearInterval(intervalId);
  }, [currentIndex, slides.length]);
  return (
    <>
      <Head>
        <title>WELCARE REHAB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <header className="header_outer">
        <Header />
      </header>
      <main>
        {/*  ##### HERO SECTION START ##### */}
        <section className={styles.sectionOne_outer} style={{ backgroundImage: `url(${slides[currentIndex].image})` }}>
          <div className={styles.hero_wrapper}>
            <div className={styles.hero_inner}>
              <h1>{slides[currentIndex].h1}</h1>
              <p>{slides[currentIndex].p}</p>
              <div className={styles.contactBtn_outer}>
                <button>CONTACT US</button>
              </div>
            </div>
          </div>
        </section>
        {/*  ##### HERO SECTION  END ##### */}

        {/*  ##### ABOUT SECTION START ##### */}
        <section className="section_Outer">
          <About page={"home"} />
        </section>
        {/*  ##### ABOUT SECTION END ##### */}

        {/*  ##### PRODUCTS SECTION START ##### */}
        <section className={styles.section_Outer2}>
          <Product />
        </section>
        {/*  ##### PRODUCTS SECTION END ##### */}

        {/*  ##### GALLERY SECTION START ##### */}
        <section className={styles.section_Outer2}>
          <Gallery />
        </section>
        {/*  ##### GALLERY SECTION END ##### */}

        {/*  ##### KNOW WHAT SECTION START ##### */}
        <section>
          <div className={styles.SectionTwo_outer1} style={{ backgroundImage: `url(${background_banner.src})` }}>
            <div className={styles.SectionTwo_inner1}>
              <div className={styles.headerDiv}>
                <h1>Know what Our </h1>
                <h3>PATIENTS SAY</h3>
              </div>
            </div>
          </div>
          <div className={styles.SectionTwo_outer2}>
            <div className={styles.SectionTwo_inner2}>
              <div className={styles.sectionleft} style={{ backgroundImage: `url(${section2.src})` }}>
                <div className={styles.addressDiv}>
                  <img src={locationIcon.src} alt="" />
                  <div className={styles.address_textDiv}>
                    <h3>ADDRESS</h3>
                    <p>
                      Lorem Ipsum is simply dummy text of the printing and tThe , comes from a line in section 1.10.32.
                    </p>
                  </div>
                </div>
                <div className={styles.addressDiv}>
                  <img src={phoneIcon.src} alt="" />
                  <div className={styles.address_textDiv}>
                    <h3>PHONE</h3>
                    <p>9122141583 / 125879578</p>
                  </div>
                </div>
                <div className={styles.addressDiv}>
                  <img src={emailIcon.src} alt="" />
                  <div className={styles.address_textDiv}>
                    <h3>EMAIL</h3>
                    <p>welcareservice@gmail.com</p>
                  </div>
                </div>
              </div>
              <div className={styles.sectionright}>
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d62708.83217763793!2d76.61888781876976!3d10.788165132212388!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba86dfa087d31ad%3A0xf542d6eb7a870a56!2sPalakkad%2C%20Kerala!5e0!3m2!1sen!2sin!4v1673635417908!5m2!1sen!2sin"
                  width="900"
                  height="400"
                  allowfullscreen=""
                  loading="lazy"
                  referrerpolicy="no-referrer-when-downgrade"
                ></iframe>
              </div>
            </div>
          </div>
        </section>
        {/*  ##### KNOW WHAT  SECTION END ##### */}
      </main>
      <footer className="footer_outer">
        <Footer />
      </footer>
    </>
  );
}
