import React from "react";
import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/Header/Header";
import about_sectionBg from "../public/about_sectionBg.png";
import styles from "../styles/Orthotics.module.css";

export default function Contactus() {
  return (
    <>
      <Head>
        <title>WELCARE REHAB - ORTHOTICS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <header className="header_outer">
        <Header />
      </header>
      <main>
        {/*  ##### CONTACT SECTION START ##### */}
        <section className="section_Outer">
          <div className={styles.about_sectionImg_outer}>
            <div className={styles.sectionDiv}>
              <div className={styles.aboutUs_heading_wrapperBox}>
                <h1>SERVICES</h1>
              </div>
            </div>
          </div>
          <div className={styles.ServiceOuter}>
            <div className={styles.ServiceInner}>
              <h1>ORTHOTICS</h1>
              <div className={styles.container}>
                <div className={styles.contentWrapper}>
                  <h2>Body Segment</h2>
                  <h3>Ankle & Foot</h3>
                  <p>
                    Improper alignment, nerve damage, and neurological conditions may hinder the ability to walk and
                    move around.
                  </p>
                  <ul>
                    <li>
                      <a href="">Ankle Foot Orthoses</a>
                    </li>
                    <li>
                      <a href="">Diabetic Shoes & Inserts</a>
                    </li>
                    <li>
                      <a href="">Foot Orthoses</a>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentWrapper}>
                  <h3>Kneet</h3>
                  <p>
                    As simple as its bending functionality may seem, the knee is a complex joint intended to provide
                    smooth, aligned movement.
                  </p>
                  <ul>
                    <li>
                      <a href="">Knee Ankle Foot Orthoses</a>
                    </li>
                    <li>
                      <a href="">Knee Orthoses</a>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentWrapper}>
                  <h3>Hip</h3>
                  <p>
                    If you or your child have a hip disorder or have had hip surgery, you may require a hip orthosis to
                    stabilize the hip.
                  </p>
                  <ul>
                    <li>
                      <a href="">Read More</a>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentWrapper}>
                  <h3>Spine</h3>
                  <p>
                    Spinal orthoses, which include neck braces and back braces, are used to support and stabilize areas
                    of the body from the jaw to the lower back, including the cervical, thoracic, and lumbar spine.
                  </p>
                  <ul>
                    <li>
                      <a href="">Read More</a>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentWrapper}>
                  <h3>Upper Limb</h3>
                  <p>
                    We offer a variety of braces and supports for the shoulder, arm, elbow, wrist, and hand that can be
                    used for a range of needs, from ongoing stability to post-operative or post-injury immobilization.
                  </p>
                  <ul>
                    <li>
                      <a href="">Read More</a>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentWrapper}>
                  <h3>Chest & Head</h3>
                  <p>
                    We offer a variety of specialty orthoses and services to treat the chest and head, such as chest
                    bracing, custom burn masks, protective helmets, and post-mastectomy services.
                  </p>
                  <ul>
                    <li>
                      <a href="">Read More</a>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentWrapper}>
                  <h2>Condition</h2>
                  <p>
                    We offer a variety of custom and off-the-shelf orthoses that support the treatment of a range of
                    mobility and musculoskeletal conditions and can help manage symptoms of pain and joint strain.
                  </p>
                  <ul>
                    <li>
                      <a href="">Neuromuscular Diseases</a>
                    </li>
                    <li>
                      <a href="">DSpinal Injury</a>
                    </li>
                    <li>
                      <a href="">Osteoarthritis</a>
                    </li>
                    <li>
                      <a href="">Chronic Pain</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/*  ##### CONTACT SECTION END ##### */}
      </main>
      <footer className="footer_outer">
        <Footer />
      </footer>
    </>
  );
}
